### ISSUE TITLE
update libmapper version to 2.4.6

### ISSUE THREAD

**Issue by aburt2** [libmapper/webmapper#40]
the python binding for libmapper v2.4.5 does not seem to work on Windows 11, crashing with an **access violation error**. 

libmapper v2.4.6 fixes this (don't know how but it doesn't crash at least), can the requirements.txt be updated to use v2.4.6.

Error message below:
`
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\aniyo\Documents\GitHub\webmapper\webmapper.py", line 79, in <module>
    webmapper_dev = mpr.Device("webmapper", graph)
  File "C:\Python\lib\site-packages\libmapper\mapper.py", line 1258, in __init__
    self._obj = mpr.mpr_dev_new(cname, graph)
OSError: exception: access violation reading 0x0000000000000008
`

**Comment by malloch** [comment]
Done!

**Comment by malloch** [comment]
Updated requirements.txt:

- libmapper 2.4.6
